### ISSUE TITLE
Выделить экстерналы в отдельный модуль

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-bosphorus#2]
Для серверного рендеринга бывает нужно настроить сборку таким образом, чтобы экстерналы были в отдельном файле: 

- экстерналы вклеиваются в общий бандл ns-приложения
- расширение прототипа вьюшки происходит в nodejs-рантайме, когда получаем новый инстант ноускрипта

Кажется, было бы удобнее разделить код на два файла:

- `noscript-bosphorus.ns.js`
- `noscript-bosphorus.externals.js`

В пакете будет собранный файлик из этих двух, под тем же названием `noscript-bosphorus.js`, что сохранит обратную совместимость для обычной браузерной сборки.

В то же время, можно будет вклеить отдельный файлик с экстернелами в серверный бандл, а в nodejs-рантайме зареквайрить явно `noscript-bosphorus.ns.js`. Этот файлик должен экспортировать функцию, которая примет в качестве аргумент инстант ns, для расширения прототипа вьюшки.

**Comment by vitkarpov** [comment]
@doochik @Rebulus

**Comment by Rebulus** [comment]
@vitkarpov, мне нравится :)

**Comment by doochik** [comment]
Норм. Сделаешь?

**Comment by vitkarpov** [comment]
Да :)

**Comment by vitkarpov** [comment]
https://github.com/yandex-ui/noscript-bosphorus/pull/3

**Comment by vitkarpov** [comment]
@doochik @Rebulus посмотрите?

**Comment by vitkarpov** [comment]
Done!
