### ISSUE TITLE
yr и ns не определён в externals

### ISSUE THREAD

**Issue by i2r** [yandex-ui/noscript-bosphorus#4]
В этой строке (и ей подобных) `yr` не будет определён: https://github.com/yandex-ui/noscript-bosphorus/blob/master/noscript-bosphorus.externals.js#L9

**Comment by i2r** [comment]
@vitkarpov

**Comment by vitkarpov** [comment]
Аналогично, здесь нужно подумать про `ns`. В бандле с шаблонами его не будет.

**Comment by vitkarpov** [comment]
@doochik @i2r @rebulus

Сейчас экстерналы хотят доступа к ns, и в случае серверного рендеринга, это кажется неправильным.

Подробнее:

- есть бандл с собранными шаблонами и экстерналами
- есть бандл с ns-приложением

Что сейчас делаем для серверного рендеринга:

- на сервере создаем новый экземпляр ns
- переопределяем `ns.renderString`: он должен ходить в определенный `yr`, который будет прочитан из бандла с шаблонами и экстерналами
- читаем бандл с `ns` приложением и выполняем его так, чтобы был доступ к созданному экземпляру `ns`, в результате чего отрабатывают все декларации и т.д., записывая в кеш данные для этого `ns`
- создаем апдейт и т.д., в результате получаем `html`

Вообще говоря, кажется правильным, чтобы и экстерналы и ns-приложение были commonjs-модулями + некоторое АПИ в ns для указания `ns.renderString` на правильный рантайм (чтобы не нужно было переопределять метод, хотя может быть это и норм)

В текущей схеме, получается так, что самостоятельный бандл с экстерналами ничего не знает про ns и не может использовать `ns.assert` и `ns.log.exception`. Может имеет смысл определить в `noscript-bosphorus.externals.js` (который возвращает функцию) возможность передать `assert` и `log-exception`, который по умолчанию будут равны соответствующим методом `ns` из глобального скоупа. В нашем случае, на сервере, сделаем простую реализацию на основе `console.log`, который будет удовлетворять уже существующему интерфейсу методов.

**Comment by vitkarpov** [comment]
> В этой строке (и ей подобных) yr не будет определён

С этим все просто: нужно обернуть весь код в функцию, которая экспортируется из модуля, чтобы методы получили доступ к `yr` через замыкание

**Comment by doochik** [comment]
Они же сейчас и там commonjs модули, надо просто приватные функции затощить внутрь экспорта `externals.js`, а его сделать `fn(yr, ns)`. Т.о. можно будет туда передавать все, что угодно, с интерфейсами `ns` и `yr`.

**Comment by vitkarpov** [comment]
Экстерналы да, я про бандл с ns-приложением (его можно было бы по аналогии сделать).

**Comment by vitkarpov** [comment]
> надо просто приватные функции затащить внутрь экспорта externals.js, а его сделать fn(yr, ns)

Сейчас как: экстерналы вклеиваются в бандл с шаблонами + яте рантаймом — этот бандл ничего про ns не знает. Я имею ввиду этот бандл сделать commonjs-модулем по-хорошему.

**Comment by vitkarpov** [comment]
Собирается банлд через https://github.com/Lapple/grunt-yate

**Comment by vitkarpov** [comment]
Кажется, grunt-yate поддерживает модули — надо попробовать.

- экспортируем из экстерналов функцию, которая принимает yr и ns
- вклеиваем экстерналы в бандл, который является commonjs-модулем и так же экспортирует функцию, которая принимает дополнительно ns

**Comment by doochik** [comment]
Тогда лучше вообще отвязать `external.js` от `ns` и ловить исключения на уровне `yr.run`.

**Comment by vitkarpov** [comment]
Ну да. При таком подходе, как ты сделал, будет достаточно реализовать `ns.assert` и `ns.log.exception`, если бандл с ятем отвязан от `ns`.

**Comment by vitkarpov** [comment]
👍

**Comment by doochik** [comment]
Даже ничего делать не надо, просто сделать `throw` с нормальным описанием )

**Comment by doochik** [comment]
Всем смотреть PR

**Comment by vitkarpov** [comment]
Thanks!

**Comment by doochik** [comment]
Залил v1.0.1
